# Generated by Django 4.0.2 on 2022-04-25 17:13

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CustomUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(default='', max_length=50, unique=True)),
                ('name', models.CharField(default='', max_length=50)),
                ('profile_pic', models.FileField(help_text='Image should be in jpeg/jpg/png form and image size should be 250*250', upload_to='profile_pic')),
                ('date_of_birth', models.DateField()),
                ('category', models.CharField(default='', max_length=50)),
                ('email', models.EmailField(default='', max_length=254)),
                ('phone', models.IntegerField(default=0)),
            ],
        ),
    ]
