# Generated by Django 4.0.2 on 2022-03-10 09:21

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CustomUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(default='', max_length=50, unique=b'I01\n')),
                ('name', models.CharField(default='', max_length=50)),
                ('date_of_birth', models.DateField()),
                ('category', models.CharField(default='', max_length=50)),
                ('email', models.EmailField(default='', max_length=254)),
                ('phone', models.IntegerField(default=0)),
                ('password', models.CharField(default='', max_length=50)),
            ],
        ),
    ]
