# Generated by Django 4.0.2 on 2022-03-14 10:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_rename_username_customuser_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customuser',
            name='User',
        ),
        migrations.AddField(
            model_name='customuser',
            name='username',
            field=models.CharField(default='', max_length=50, unique=True),
        ),
    ]
