# Generated by Django 4.0.2 on 2022-03-14 10:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_remove_customuser_user_customuser_username'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='profile_pic',
            field=models.ImageField(default=1, help_text='Image should be in jpeg/jpg/png form and image size should be 250*250', upload_to='profile-pic'),
            preserve_default=False,
        ),
    ]
