# Generated by Django 4.0.2 on 2022-03-14 11:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_customuser_profile_pic'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='profile_pic',
            field=models.FileField(help_text='Image should be in jpeg/jpg/png form and image size should be 250*250', upload_to='profile-pic'),
        ),
    ]
