# Generated by Django 4.0.2 on 2022-03-10 09:21

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='myproduct',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', max_length=50)),
                ('sown', models.DateField()),
                ('reap', models.DateField()),
                ('land_area', models.BigIntegerField(default=0)),
                ('area', models.CharField(default='', max_length=50)),
            ],
        ),
    ]
