# Generated by Django 4.0.2 on 2022-03-16 07:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0013_alter_customuser_profile_pic'),
        ('farmers', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='myproduct',
            name='user',
            field=models.ForeignKey(default=3, on_delete=django.db.models.deletion.CASCADE, to='accounts.customuser'),
            preserve_default=False,
        ),
    ]
