# Generated by Django 4.0.2 on 2022-03-24 06:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('farmers', '0002_myproduct_user'),
    ]

    operations = [
        migrations.RenameField(
            model_name='myproduct',
            old_name='area',
            new_name='address',
        ),
    ]
